# Generated by Django 5.2 on 2025-08-31 13:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_mvp_client_model"),
        ("services", "0001_initial"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the record is soft deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "scheduled_start_time",
                    models.DateTimeField(
                        help_text="Scheduled start time for the appointment"
                    ),
                ),
                (
                    "scheduled_end_time",
                    models.DateTimeField(
                        help_text="Scheduled end time for the appointment"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Confirmation"),
                            ("confirmed", "Confirmed"),
                            ("checked_in", "Checked In"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        help_text="Current status of the appointment",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Payment Pending"),
                            ("partial", "Partially Paid"),
                            ("paid", "Fully Paid"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        help_text="Payment status of the appointment",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Final price for the appointment",
                        max_digits=8,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the appointment"
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(
                        blank=True, help_text="Reason for cancellation (if applicable)"
                    ),
                ),
                (
                    "actual_start_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Actual start time of the service",
                        null=True,
                    ),
                ),
                (
                    "actual_end_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Actual end time of the service",
                        null=True,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Client for this appointment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="clients.client",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        help_text="Service to be provided",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="services.service",
                    ),
                ),
                (
                    "staff_member",
                    models.ForeignKey(
                        help_text="Staff member providing the service",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="staff.staffprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
                "db_table": "appointments",
                "ordering": ["-scheduled_start_time"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["scheduled_start_time"],
                        name="appointment_schedul_d9b807_idx",
                    ),
                    models.Index(
                        fields=["status"], name="appointment_status_9fecd6_idx"
                    ),
                    models.Index(
                        fields=["client"], name="appointment_client__2834cc_idx"
                    ),
                    models.Index(
                        fields=["staff_member"], name="appointment_staff_m_ab7009_idx"
                    ),
                    models.Index(
                        fields=["service"], name="appointment_service_8b5966_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("scheduled_start_time__lt", models.F("scheduled_end_time"))
                        ),
                        name="valid_appointment_time_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("price__gte", Decimal("0.00"))),
                        name="positive_appointment_price",
                    ),
                ],
            },
        ),
    ]
