# Generated by Django 5.2 on 2025-08-29 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the record is soft deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Client first name",
                        max_length=50,
                        verbose_name="First Name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Client last name",
                        max_length=50,
                        verbose_name="Last Name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Client email for notifications",
                        max_length=254,
                        unique=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Client phone number for SMS notifications",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Phone number must be entered in format: "+999999999". Up to 15 digits allowed.',
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "allergies",
                    models.TextField(
                        blank=True,
                        help_text="Any allergies or sensitivities to products",
                        verbose_name="Allergies",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the client",
                        verbose_name="Notes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "db_table": "clients",
                "ordering": ["last_name", "first_name"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["last_name", "first_name"],
                        name="clients_last_na_7dc725_idx",
                    ),
                    models.Index(fields=["email"], name="clients_email_4c8bec_idx"),
                ],
            },
        ),
    ]
